//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.10 at 08:12:56 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ahrendee.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ahrendee.courses;
